package com.fatalitiii.utilfatal;

import com.fatalitiii.utilfatal.utils.ModInfo;
import com.fatalitiii.utilfatal.mobs.getAllMobs;

import net.minecraft.util.EnumChatFormatting;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.Mod.Instance;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPostInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;

/**
 * @author Fatalitiii
 * @name UtilFatal.java
 * @Comment Must be initialised in mod so that you can access the mob array
 *          list.
 */
@Mod(modid = ModInfo.MOD_ID, name = ModInfo.MOD_NAME, version = ModInfo.VERSION)
public class UtilFatal {

	@Instance(ModInfo.MOD_ID)
	public static UtilFatal Instance;

	private static final getAllMobs mobs = new getAllMobs();

	@EventHandler
	public void preInit(FMLPreInitializationEvent event) {
		ModMetadata data = event.getModMetadata();
		data.autogenerated = false;
		data.name = EnumChatFormatting.RED + ModInfo.MOD_NAME;
		data.credits = EnumChatFormatting.BLUE + "Fatalitiii";
		data.authorList.add("Fatalitiii");
		data.description = "Utility Fatalitiii, wow thats a mouth full :P. This is a mod that has nice utilitys that can come in handy when developing mods.";
		data.logoFile = "assets/utilfatal/textures/misc/logo.png";
	}

	@EventHandler
	public void init(FMLInitializationEvent event) {
	}

	@SuppressWarnings("static-access")
	@EventHandler
	public void postInit(FMLPostInitializationEvent event) {
		Instance.mobs.initMobs();
	}

	/**
	 * @Comment Call this method to return the getMobs class instance.
	 */
	@SuppressWarnings("static-access")
	public getAllMobs getMobs() {
		return Instance.mobs;
	}

}
